# -*- coding: utf-8 -*-
"""IRC_client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12w462Bhfi9I7hp-rIdUtwFFqDanCc7qa
"""

import threading
import socket
import sys

username = input("Enter your full name: ")
threads = []
FORMAT = 'utf-8'
#To start the connection
#server =  socket.gethostbyname(socket.gethostname())
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

client.connect(('127.0.0.1', 55555))

#start_chat()

def get_message():
  connected = True
  while connected:
        try:
            message = client.recv(2048)
            raw_message = message.decode(FORMAT)
            if raw_message == 'QUIT':
              sys.exit(2)

            if raw_message == 'NICK':
                client.send(username.encode(FORMAT))
            else:
                print(raw_message)
        except Exception as e:
            client.close()
            sys.exit(2)

def send_message():
  connected = True
  while connected:
        raw_message = '{} {}'.format(username, input(''))
        try:
            client.send(raw_message.encode('utf-8'))
        except:
            client.close()
            sys.exit(0)

def start_chat():
    get_message_thread = threading.Thread(target=get_message).start()
    #get_message_thread.start()
    threads.append(get_message_thread)
    send_message_thread = threading.Thread(target=send_message).start()
    #send_message_thread.start()
    threads.append(send_message_thread)
start_chat()